name = "picazo-site"
type = "javascript"
compatibility_date = "2025-01-01"

[[kv_namespaces]]
binding = "GALLERY"
id = "picazo_gallery"
preview_id = "picazo_gallery_preview"

[env.production]
name = "picazo-site-production"

[[env.production.kv_namespaces]]
binding = "GALLERY"
id = "picazo_gallery"
