name = "picazo-site"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[[kv_namespaces]]
binding = "GALLERY"
id = "7ccacf2ad5bf4fdda7fc960841fd68e8"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "picazo-images"

[env.production]
name = "picazo-site-production"

[[env.production.kv_namespaces]]
binding = "GALLERY"
id = "7ccacf2ad5bf4fdda7fc960841fd68e8"

[[env.production.r2_buckets]]
binding = "IMAGES"
bucket_name = "picazo-images"
